package ktor.sportsapi.players

import org.bson.codecs.pojo.annotations.BsonId
import org.litote.kmongo.Id
import org.litote.kmongo.newId

data class Player(
    @BsonId
    val id: Id<Int> = newId(),
    var idPlayer: String?,
    var dateBorn: String?,
    var dateSigned: String?,
    var idAPIfootball: String?,
    var idPlayerManager: String?,
    var idSoccerXML: String?,
    var idTeam: String?,
    var idTeam2: String?,
    var idTeamNational: String?,
    var intLoved: String?,
    var intSoccerXMLTeamID: String?,
    var strAgent: String?,
    var strBanner: String?,
    var strBirthLocation: String?,
    var strCollege: String?,
    var strCreativeCommons: String?,
    var strCutout: String?,
    var strDescriptionCN: String?,
    var strDescriptionDE: String?,
    var strDescriptionEN: String?,
    var strDescriptionES: String?,
    var strDescriptionFR: String?,
    var strDescriptionHU: String?,
    var strDescriptionIL: String?,
    var strDescriptionIT: String?,
    var strDescriptionJP: String?,
    var strDescriptionNL: String?,
    var strDescriptionNO: String?,
    var strDescriptionPL: String?,
    var strDescriptionPT: String?,
    var strDescriptionRU: String?,
    var strDescriptionSE: String?,
    var strFacebook: String?,
    var strFanart1: String?,
    var strFanart2: String?,
    var strFanart3: String?,
    var strFanart4: String?,
    var strGender: String?,
    var strHeight: String?,
    var strInstagram: String?,
    var strKit: String?,
    var strLocked: String?,
    var strNationality: String?,
    var strNumber: String?,
    var strOutfitter: String?,
    var strPlayer: String?,
    var strPosition: String?,
    var strRender: String?,
    var strSide: String?,
    var strSigning: String?,
    var strSport: String?,
    var strTeam: String?,
    var strTeam2: String?,
    var strThumb: String?,
    var strTwitter: String?,
    var strWage: String?,
    var strWebsite: String?,
    var strWeight: String?,
    var strYoutube: String?
)